
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class GhostMove : MonoBehaviour
{
    public float speed = 0.2f;
    public GameObject[] wayPointsGos;
    private List<Vector3> wayPoints = new List<Vector3>();
    private int index = 0;
    private Vector3 startPos;
    SpriteRenderer MatPacman;
    SpriteRenderer MatPacGhost;
    
    private void Start()
    {
        //startPos = transform.position + new Vector3(0, 3, 0);
        startPos = transform.position + new Vector3(0, 0, 0);
        LoadAPath(wayPointsGos[GameManager.Instance.usingIndex[0]]);
    }
    private void FixedUpdate()
    {
        if (transform.position != wayPoints[index])
        {
            Vector2 temp = Vector2.MoveTowards(transform.position, wayPoints[index], speed);
            GetComponent<Rigidbody2D>().MovePosition(temp);
        }
        else
        {
            index++;
           if( index >= wayPoints.Count)
            {
                index = 0;
                LoadAPath(wayPointsGos[Random.Range(0, wayPointsGos.Length)]);

            }
         }
        Vector2 dir = wayPoints[index]- transform.position;
        GetComponent<Animator>().SetFloat("DirX", dir.x);
        GetComponent<Animator>().SetFloat("DirY", dir.y);
       

    }
    private void LoadAPath(GameObject go)
    {
        wayPoints.Clear();
        foreach (Transform t in go.transform)
        {
            wayPoints.Add(t.position);
        }
        wayPoints.Insert(0, startPos);
        wayPoints.Add(startPos);
    }
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.gameObject.name == "Pacman")
        {
            MatPacman = collision.gameObject.GetComponent<SpriteRenderer>();
            MatPacGhost = gameObject.GetComponent<SpriteRenderer>();
            if ((MatPacman.color.g- MatPacGhost.color.g)<0.001)
            {
                Destroy(gameObject);
            }
            else
            {
                collision.gameObject.SetActive(false);
                GameManager.Instance.gamePanel.SetActive(false);
                Instantiate(GameManager.Instance.gameoverPrefab);
                Invoke("Restart", 3f);
            }
            GameManager.Instance.nowEat += 1;
        }
        
    }
    public void Restart()
    {
        SceneManager.LoadScene(0);
        
    }
}
